definitions:
  entities.Book:
    properties:
      author:
        type: string
      cover_image_url:
        type: string
      description:
        type: string
      id:
        type: integer
      isbn:
        type: string
      number_of_pages:
        type: integer
      publication_date:
        type: string
      title:
        type: string
    type: object
info:
  contact:
    email: bambang.handoko12@gmail.com
    name: Bambang Handoko (Ando)
  description: This is a sample API for managing books in the library.
  title: Mini Books Library API
  version: "1.0"
paths:
  /books:
    get:
      consumes:
      - application/json
      description: Retrieve a list of all books in the library
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entities.Book'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: true
            type: object
      summary: Get all books
      tags:
      - books
swagger: "2.0"
